import random
import StarTSPImage
from PIL import Image, ImageDraw, ImageFont

col1 = [
    'Keer',
    'Ronium',
    'Jiinan',
    'Riann',
    'Bama',
    'Shyne',
    'Fenn',
    'Kavra',
    'Audice',
    'Aletra',
    'Eera',
    'Erge',
    'Deryk',
    'Kitrep',
    'Tomas',
    'Cal',
    'Ike',
    'Jami',
    'Rhea',
    'Myyse',
    'Anakin',
    'Orion',
    'Raddi',
    'Callista',
    'Neiki',
    'Rowana',
    'Erri',
    'Rik',
    'Thoy',
    'Dan',
    'Jepheg',
    'Ai',
    'Sy',
    'Kaidi',
    'Jor',
    'Astr',
    'Das',
    'Ram',
    'Mal',
    'Num',
    'Tor',
    'Ren',
    'Kaida',
    'Room',
    'Anyk',
    'Cassi',
    'Nook',
    'Luka',
    'Perti',
    'Iir',
    'Zara',
    'Kylo',
    'Finn',
    'Rey',
    'Poe',
    'Maz',
    'Hux',
    'Snoke',
    'Holdo',
    'Chirrut',
    'Baze',
    'Jyn',
    'Cassian',
    'Bodhi',
    'Galen',
    'Krennic',
    'Saw',
    'Ezra',
    'Kanan',
    'Hera',
    'Sabine',
    'Zeb',
    'Thrawn',
    'Ahsoka',
    'Rex',
    'Cody',
    'Fives',
    'Echo',
    'Ventress',
    'Savage',
    'Maul',
    'Qui-Gon',
    'Mace',
    'Aayla',
    'Kit',
    'Plo',
    'Shaak',
    'Luminara',
    'Barriss',
    'Dooku',
    'Grievous',
    'Tarkin',
    'Veers',
    'Piett',
    'Ozzel',
    'Needa',
    'Jerjerrod',
    'Tagge',
    'Pryde',
    'Hux',
    'Phasma',
    'DJ',
    'Rose',
    'Paige',
    'Zorii',
    'Babu',
    'Jannah',
    'Maz',
    'Enfys',
    'Qi\'ra',
    'Dryden',
    'Tobias',
    'Val',
    'Rio',
    'L3-37',
    'Beckett',
    'Aurra',
    'Cad',
    'Embo',
    'Sugi'
]
col2 = [
'Reyaltor',
'Hoorle',
'Rey ',
'Galad',
'Alavai',
'Rivas',
'Basai',
'Skyless',
'Flahar',
'Mollek',
'Sol',
'Cooc',
'Luunalle',
'Thoop',
'Kovani',
'Raisuun',
'Zayelty',
'Jupitus',
'Botos',
'Kenzee',
'Narhwal',
'Taske',
'Wenden',
'Mantisar',
'Rato',
'Kahlu',
'Rool',
'Eclipsy',
'Andor',
'Repsel',
'Allagru',
'Starcos',
'Andromias',
'Dindag',
'Sllor',
'Ripnar',
'Starcross',
'Moony',
'Earthren',
'Walker',
'Eskildar',
'Tineslack',
'Lazee',
'Cheddar',
'Bisqit',
'Neerd',
'Brainbomb',
'Hardnut',
'Booster',
'Flash'
]
col3 = [
'Chagrian',
'Jedi',
'Clawdite',
'Gand',
'Arcona',
'Dresselian',
'Devaronian',
'Amanin',
'Snivvian',
'Ishi Tib',
'Gungan',
'Muun',
'Duros',
'Crolute',
'Bith',
'Sith',
'Jedi',
'Bothan',
'Gamorrean',
'Rodian',
'Mon Calamari',
'Ewok',
'Twi\'lek',
'Togruta',
'Hutt',
'Sand People',
'Jawa',
'Yoda',
'Zabrak',
'Wookiee',
'Jedi',
'Chagrian',
'Jedi',
'Clawdite',
'Gand',
'Arcona',
'Dresselian',
'Devaronian',
'Amanin',
'Snivvian',
'Ishi Tib',
'Gungan',
'Muun',
'Duros',
'Crolute',
'Bith',
'Sith',
'Jedi',
'Bothan',
'Gamorrean'
]
col4 = [
'Knight',
'Lord',
'Smuggler',
'StormTrooper',
'Captain',
'Pirate',
'Janitor',
'Princess',
'Councillor',
'Senator',
'Rebel ',
'Brawler',
'Bounty Hunter',
'Commando',
'Artisan',
'Logger',
'Master',
'Beastmaster',
'Bookie',
'Rancor Trainer',
'Beast Charmer',
'Trader',
'Raider',
'Clone',
'Slave',
'Officer',
'Klingon',
'Customer Service Assistant',
'Dishwasher',
'Den-mother',
'Gamblerer',
'Admiral',
'Hermit',
'Imperial Hunter',
'Tour Guide',
'Farmer',
'Commando',
'Crime Lord',
'Outlaw',
'Vigo',
'Chef',
'Doctor',
'Medic',
'Broker',
'Trooper',
'Scout',
'Cook',
'Technician',
'Plumber',
'Singer'
]
col5 = [
'I am your father!',
'Use the force...use it or loose it!',
'Help me, you\'re my only hope',
'I\'ve been waiting for you',
'I find your lack of faith disturbing',
'The Force will be with you. Always.',
'Never tell me the odds!',
'Do. Or do not. There is no try',
'When gone am I, the last of the Jedi will you be',
'You are just a simple being trying to make your way in the universe.',
'You are the Chosen One.',
'You are no Jedi.',
'You are going down a path I cannot follow!',
'Oh my.',
'I sense great fear in you',
'Save the Rebellion. Save the dream',
'The strongest stars have hearts of kyber.',
'Strike me down, and I will become more powerful than you could possibly imagine.',
'These aren\'t the droids you\'re looking for',
'You came in that thing? You\'re braver than I thought.',
'Aren\'t you a little short for a Stormtrooper?',
'There is good in you, I\'ve felt it.',
'You\'re just a child with a mask',
'My disappointment in your performance cannot be overstated.',
'Great, kid. Don\'t get cocky.',
'Traveling through hyperspace ain\'t like dusting crops, farm boy',
'Laugh it up, foozeball.',
'The force is strong with this one.',
'Obi-Wan has taught you well.',
'You are shorter than I expected.',
'Be careful not to choke on your aspirations.',
'When 900 years old, you reach. Look as good, you will not.',
'Fear is the path to the dark side.',
'Ahh, hard to see, the Dark Side is',
'Mmm. Lost a planet, you have. How embarrassing.',
'Judge me by my size, do you?',
'Welcome to the Dark Side...we have cookies.',
'Fear is the path to the Dark Side.',
'Someday you will be the most powerful Jedi ever.',
'It was said that you would destroy the Sith, not join them.',
'I am rather embarrassed, but it appears that you are to be the main course at a banquet in my honor.',
'Use the Force!',
'We meet again, at last. The circle is now complete. When I left you, I was but the learner; now I am the master!',
'Sith happens...',
'I\'ve got a bad feeling about this',
'Help me, you\'re my only hope',
'I\'ve been waiting for you',
'I find your lack of faith disturbing',
'The Force will be with you. Always.',
'Laugh it up, fuzzball.',
'May the Force be with you.',
'I\'m one with the Force. The Force is with me.',
'Chewie, we\'re home.',
'That\'s no moon. It\'s a space station.',
'It\'s a trap!',
'So this is how liberty dies...with thunderous applause.',
'I am a Jedi, like my father before me.',
'Now, young Skywalker, you will die.',
'I\'m just a simple man trying to make my way in the universe.',
'Power! Unlimited power!',
'I don\'t like sand. It\'s coarse and rough and irritating and it gets everywhere.',
'There\'s always a bigger fish.',
'Now this is podracing!',
'I\'m haunted by the kiss that you should never have given me.',
'You were the chosen one! It was said that you would destroy the Sith, not join them!',
'Hello there!',
'Another happy landing.',
'This is where the fun begins.',
'I hate it when he does that.',
'You were right about one thing, Master. The negotiations were short.',
'The dark side of the Force is a pathway to many abilities some consider to be unnatural.',
'I\'ve been looking forward to this.',
'Twice the pride, double the fall.',
'So uncivilized.',
'Your focus determines your reality.',
'In my experience, there\'s no such thing as luck.',
'I\'ve got a bad feeling about this.',
'Let the past die. Kill it if you have to.',
'That\'s how we\'re gonna win. Not fighting what we hate, saving what we love.',
'Amazing. Every word of what you just said was wrong.',
'The greatest teacher, failure is.',
'We are what they grow beyond. That is the true burden of all masters.',
'Hope is like the sun. If you only believe in it when you can see it, you\'ll never make it through the night.',
'Every word in that sentence was wrong.',
'The belonging you seek is not behind you... it is ahead.',
'I will finish what you started.',
'That\'s not how the Force works!',
'Rebellions are built on hope.',
'I am one with the Force and the Force is with me.',
'You can\'t stop the change, any more than you can stop the suns from setting.',
'The Force is not a power you have. It\'s not about lifting rocks. It\'s the energy between all things, a tension, a balance, that binds the universe together.',
'We\'ll always be with you. No one\'s ever really gone.',
'I bypassed the compressor!',
'Impressive. Every word in that sentence was wrong.',
'This is the way.',
'I have spoken.',
'I like those odds.',
'I can bring you in warm, or I can bring you in cold.',
'Droids are not meant to be servants. They are equals. They have hopes and dreams of their own.',
'You have failed me for the last time, Admiral.',
'If you strike me down, I shall become more powerful than you can possibly imagine.',
'I\'m a Mandalorian. Weapons are part of my religion.',
'I\'m a person and my name is Anakin!',
'There\'s too many of them!',
'You underestimate my power!',
'I don\'t care what universe you\'re from, that\'s got to hurt!',
'The garbage will do!',
'Boring conversation anyway.',
'It\'s not my fault!',
'I\'ve altered the deal. Pray I don\'t alter it any further.',
'No, I am your father.',
'Do it.',
'Execute Order 66.',
'A fine addition to my collection.',
'Hello there!',
'You were my brother, Anakin! I loved you!',
'I am the Senate!',
'It\'s over, Anakin! I have the high ground!',
'So this is how liberty dies... with thunderous applause.',
'I\'m just a simple man trying to make my way in the universe.',
'Your clones are very impressive. You must be very proud.',
'We stand here amidst my achievement, not yours!',
'Be careful not to choke on your aspirations, Director.',
'I find that answer vague and unconvincing.',
'You\'re all rebels, aren\'t you?',
'I am one with the Force, and the Force is with me.',
'The Force is strong with this one.',
'I\'ve got a bad feeling about this.',
'May the Force be with you.',
'Do. Or do not. There is no try.',
'No. I am your father.',
'Luke, you can destroy the Emperor. He has foreseen this. It is your destiny. Join me, and together we can rule the galaxy as father and son.',
'I\'m one with the Force. The Force is with me.',
'Chewie, we\'re home.',
'These aren\'t the droids you\'re looking for.',
'It\'s a trap!',
'So this is how liberty dies...with thunderous applause.',
'Hello there!',
'I don\'t like sand. It\'s coarse and rough and irritating and it gets everywhere.',
'Now this is podracing!',
'You were the chosen one! It was said that you would destroy the Sith, not join them!',
'I am a Jedi, like my father before me.',
'Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.',
'There\'s always a bigger fish.',
'In my experience, there is no such thing as luck.',
'I\'ve got a bad feeling about this.',
'Let the past die. Kill it if you have to.',
'The greatest teacher, failure is.',
'We are what they grow beyond. That is the true burden of all masters.',
'Hope is like the sun. If you only believe in it when you can see it, you\'ll never make it through the night.',
'Every word in that sentence was wrong.',
'The belonging you seek is not behind you... it is ahead.',
'I will finish what you started.',
'That\'s not how the Force works!',
'Rebellions are built on hope.',
'I am one with the Force and the Force is with me.',
'You can\'t stop the change, any more than you can stop the suns from setting.',
'The Force is not a power you have. It\'s not about lifting rocks. It\'s the energy between all things, a tension, a balance, that binds the universe together.',
'We\'ll always be with you. No one\'s ever really gone.',
'I bypassed the compressor!',
'Impressive. Every word in that sentence was wrong.',
'This is the way.',
'I have spoken.',
'I like those odds.',
'I can bring you in warm, or I can bring you in cold.',
'Droids are not meant to be servants. They are equals. They have hopes and dreams of their own.'
]

p1 = col1[random.randint(0,len(col1)-1)]
p2 = col2[random.randint(0,len(col2)-1)]
p3 = col3[random.randint(0,len(col3)-1)]
p4 = col4[random.randint(0,len(col4)-1)]
p5 = col5[random.randint(0,len(col5)-1)]
name = p1 + " " + p2
l1 = p3 + " " + p4
l2 = p5

message = f"Greetings {p1} {p2}!\n{l1} I see you are.\n{l2}"

def text_to_bitmap(text, output_path, font_size=25, image_size=(500, 200), bg_color="white", text_color="black"):
    # Create a new image with white background
    img = Image.new('RGB', image_size, color=bg_color)
    
    # Create a draw object
    draw = ImageDraw.Draw(img)
    
    # Load a font
    try:
        font = ImageFont.truetype(r"/usr/share/fonts/truetype/roboto-slab/RobotoSlab-Thin.ttf", font_size)
    except OSError:
        font = ImageFont.load_default()
    
    font.size = font_size
    
    # Calculate text position to center it
    bbox = draw.textbbox((0, 0), text, font=font, align='center')
    text_width = bbox[2] - bbox[0]
    text_height = bbox[3] - bbox[1]
    position = ((image_size[0] - text_width) / 2, (image_size[1] - text_height) / 2)
    
    # Draw the text on the image
    draw.text(position, text, font=font, fill=text_color)
    
    # Save the image
    img.save(output_path)

text_to_bitmap(message, "output.bmp")

output_path = 'output.bmp'

raster = StarTSPImage.imageFileToRaster("output.bmp", cut=True)

printer = open('/dev/usb/lp3', 'wb')
printer.write(raster)